# from CLI run SECRET_KEY=your_secret_key_here TMDB_API_KEY=your_tmdb_api_key_here docker-compose up
version: '3.8'

services:
  web:
    image: matiasmtl/movie-picker:latest
    ports:
      - "32778:5000"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY?TMDB API key is required}
      - MOVIES_FILE=/app/src/data/movies.json
      - TV_SHOWS_FILE=/app/src/data/tv_shows.json
    volumes:
      - ./src/data:/app/src/data # Bind mount local data directory instead
    restart: unless-stopped
