version: '3.8'

services:
  web:
    image: matiasmtl/movie-picker:latest # Specify your Docker Hub image
    # build: .  # Comment out or remove this line when using image from Docker Hub
    ports:
      - "32778:5000" # Change 32778 to your desired external port
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    restart: unless-stopped
