version: '3.8'

services:
  web:
    image: matiasmtl/movie-picker:latest
    ports:
      - "32778:5000"
    environment:
      - SECRET_KEY=change_this_in_production
    volumes:
      - movie-data:/app/src
    restart: unless-stopped

volumes:
  movie-data:
